#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing dependencies...\n"
echo "=> Installing python3-pip...\n"
sudo apt-get -y install python3-pip
echo "=> Installing vcgencmd...\n"
sudo pip3 install vcgencmd
echo "=> Installing setuptools...\n"
sudo pip3 install setuptools
echo "=> Installing gpiozero...\n"
sudo pip3 install gpiozero
echo "=> Installing RPi.GPIO...\n"
sudo pip3 install RPi.GPIO

echo "=> Installing fan controller...\n"
sudo cp fancontrol.py /usr/local/bin/
sudo chmod +x /usr/local/bin/fancontrol.py

echo "=> Starting fan controller...\n"
sudo cp fancontrol.sh /etc/init.d/
sudo chmod +x /etc/init.d/fancontrol.sh

sudo update-rc.d fancontrol.sh defaults
sudo /etc/init.d/fancontrol.sh start

echo "Fan controller installed."
